EnerGym_folder/EnerGym/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, re_path, include
from django.views.generic.base import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('EnerGym/', include('gestione_palestra.urls')),
    path('EnerGym/', include('lezioni.urls')),
    path('EnerGym/', include('forum.urls')),
    re_path(r'^$', RedirectView.as_view(url='EnerGym', permanent=False), name='index')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

EnerGym_folder/forum/urls.py
from django.contrib.staticfiles.storage import staticfiles_storage
from django.urls import path
from django.urls import re_path
from django.views.generic import RedirectView
from . import views

app_name = 'forum'

urlpatterns = [
    path('forum', views.forum_homepage, name='forum_home'),
    path('forum/topic/<int:id>', views.topic, name='topic_info'),
    path('forum/topic/add_comment', views.crea_commento, name='crea_commento'),
    path('forum/topic/update_commento/<int:pk>', views.update_commento, name='update_commento'),
    path('forum/topic/delete_commento/<int:pk>', views.delete_commento, name='delete_commento'),
    path('forum/topic/add_topic', views.add_topic, name='add_topic'),
    path('forum/topic/delete_topic/<int:pk>', views.delete_topic, name='delete_topic'),
    path('favicon.ico', RedirectView.as_view(url=staticfiles_storage.url('img/Energym.ico'))),
    re_path(r'^$', RedirectView.as_view(url='homepage', permanent=False), name='index'),
]

EnerGym_folder/gestione_palestra/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.urls import re_path
from django.contrib.auth import views as auth_views
from django.views.generic.base import RedirectView

from . import views

app_name = 'gestione_palestra'

urlpatterns = [
    path('homepage', views.homepage, name='homepage'),
    path('insegnanti', views.istruttori, name='insegnanti'),
    path('insegnanti/<int:id>', views.istruttore_info, name='insegnante_info'),
    path('contatti', views.contatti, name='contatti'),
    path('notizie/<int:id>', views.notizia_info, name='notizia_info'),
    path('notizie', views.notizie, name='notizie'),
    path('profile/<int:pk>', views.ShowProfile.as_view(), name='profile'),
    path('modifica/<int:pk>', views.ModifyUser.as_view(), name='modifica_user'),
    path('modificaPassword', views.PasswordChangeView, name='modica_password'),
    path('gallery', views.gallery, name='gallery'),
    path('logout', auth_views.LogoutView.as_view(), name='logout'),
    path('corsi', views.corsi, name='corsi'),
    path('corsi/<int:id>', views.corso_info, name='corso_info'),
    path('registrazione', views.SignUp.as_view(), name='registrazione'),
    path('login', auth_views.LoginView.as_view(), name='login'),
    path('check_username_unique', views.check_username_is_unique, name='check-username-unique'),
    re_path(r'^$', RedirectView.as_view(url='homepage', permanent=False), name='index'),
]

EnerGym_folder/lezioni/urls.py
from django.urls import re_path
from django.urls import path
from django.views.generic import RedirectView
from . import views

app_name = 'lezioni'

urlpatterns = [
    path('lezioni', views.lezioni, name='lezioni'),
    path('lezioni/le_mie_lezioni/<int:id>', views.gestione_lezioni, name='gestione_lezioni'),
    path('lezioni/crea', views.crea_lezione, name='crea_lezione'),
    path('lezioni/update/<int:pk>', views.update_lezione, name='update_lezione'),
    path('lezioni/delete/<int:pk>', views.delete_lezione, name='delete_lezione'),
    path('lezioni/prenotate/<int:id>', views.prenotazioni, name='prenotazioni'),
    path('lezioni/prenota', views.Prenota.as_view(), name='prenota'),
    path('lezioni/prenota/delete', views.DeletePrenotazione.as_view(), name='delete_prenotazione'),
    re_path(r'^$', RedirectView.as_view(url='homepage', permanent=False), name='index'),
]

EnerGym_folder/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link href="https://use.fontawesome.com/releases/v5.0.7/css/all.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.21/css/jquery.dataTables.css">
    <link rel="shortcut icon" type="image/png" href="{% static 'img/Energym.ico' %}"/>

    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.js" defer></script>

    {% block style %}
    {% endblock %}

    <style>

        #profile_img {
            height: 40px;
            width: 40px;
            object-fit: cover;
            border-radius: 50%;
            margin: auto;
        }
    </style>

    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<header>
    <nav class="navbar navbar-expand navbar-light " >
        <a class="navbar-brand" href="{% url 'gestione_palestra:homepage' %}">
            <img  src="{% static 'img/Energym_logo.JPG' %}" width="140" height="40" class="d-inline-block align-top" alt="" loading="lazy">
        </a>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link rounded" href="{% url 'gestione_palestra:homepage' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link rounded" href="{% url 'gestione_palestra:insegnanti' %}">Istruttori</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link rounded" href="{% url 'gestione_palestra:corsi' %}" id="navbarDropdown" role="button" aria-haspopup="true" aria-expanded="false">
                        Corsi
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        {% if user.is_authenticated %}
                            <a class="dropdown-item" href="{% url 'lezioni:prenotazioni' user.id %}">Lezioni nel mio programma</a>
                            <a class="dropdown-item" href="{% url 'lezioni:lezioni' %}">Tutte le lezioni</a>
                            <div class="dropdown-divider"></div>
                        {% endif %}
                        {% for corso in Corsi %}
                            <a class="dropdown-item" href="{% url 'gestione_palestra:corso_info' corso.id %}">{{ corso.nome }}</a>
                        {% endfor %}
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link rounded" href="{% url 'gestione_palestra:gallery' %}">Gallery</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link rounded" href="{% url 'gestione_palestra:notizie' %}">News</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link rounded" href="{% url 'forum:forum_home' %}">Forum</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link rounded" href="{% url 'gestione_palestra:contatti'%}">Contattaci</a>
                </li>
            </ul>
            {% if user.is_authenticated %}
                <ul class="navbar-nav ml-auto" >
                    <li>
                        <a href="{% url 'gestione_palestra:profile' user.id %}"><img id="profile_img" src="{{ user.profile_img.url }}" class="img d-block ui-w-40 rounded-circle" alt=""></a>
                    </li>
                    {% if user.is_insegnante %}
                        <li class="nav-item">
                            <a class="nav-link">|</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link rounded" href="{% url 'lezioni:gestione_lezioni' user.id %}">Le mie lezioni</a>
                        </li>
                    {% endif %}
                    <a class="nav-link">|</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link rounded" href="{% url 'gestione_palestra:logout'%}">Logout</a>
                    </li>
                </ul>
            {% else %}
                <ul class="navbar-nav my-2 my-lg-0">
                    <li class="nav-item">
                        <a class="nav-link rounded" href="{% url 'gestione_palestra:login'%}">Log In</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link">|</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link rounded" href="{% url 'gestione_palestra:registrazione'%}">Sign Up</a>
                    </li>
                </ul>
            {% endif %}
        </div>
    </nav>
</header>

{% block body %}{% endblock %}




<script
        src="https://code.jquery.com/jquery-3.4.1.min.js"
        integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
        crossorigin="anonymous"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"
        integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU="
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
        integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
        crossorigin="anonymous"></script>

{% block script %}{% endblock %}

</body>
</html>