EnerGym_folder/EnerGym/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, re_path, include
from django.views.generic.base import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('EnerGym/', include('gestione_palestra.urls')),
    path('EnerGym/', include('lezioni.urls')),
    path('EnerGym/', include('forum.urls')),
    re_path(r'^$', RedirectView.as_view(url='EnerGym', permanent=False), name='index')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

EnerGym_folder/forum/urls.py
from django.contrib.staticfiles.storage import staticfiles_storage
from django.urls import path
from django.urls import re_path
from django.views.generic import RedirectView
from . import views

app_name = 'forum'

urlpatterns = [
    path('forum', views.forum_homepage, name='forum_home'),
    path('forum/topic/<int:id>', views.topic, name='topic_info'),
    path('forum/topic/add_comment', views.crea_commento, name='crea_commento'),
    path('forum/topic/update_commento/<int:pk>', views.update_commento, name='update_commento'),
    path('forum/topic/delete_commento/<int:pk>', views.delete_commento, name='delete_commento'),
    path('forum/topic/add_topic', views.add_topic, name='add_topic'),
    path('forum/topic/delete_topic/<int:pk>', views.delete_topic, name='delete_topic'),
    path('favicon.ico', RedirectView.as_view(url=staticfiles_storage.url('img/Energym.ico'))),
    re_path(r'^$', RedirectView.as_view(url='homepage', permanent=False), name='index'),
]

EnerGym_folder/gestione_palestra/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.urls import re_path
from django.contrib.auth import views as auth_views
from django.views.generic.base import RedirectView

from . import views

app_name = 'gestione_palestra'

urlpatterns = [
    path('homepage', views.homepage, name='homepage'),
    path('insegnanti', views.istruttori, name='insegnanti'),
    path('insegnanti/<int:id>', views.istruttore_info, name='insegnante_info'),
    path('contatti', views.contatti, name='contatti'),
    path('notizie/<int:id>', views.notizia_info, name='notizia_info'),
    path('notizie', views.notizie, name='notizie'),
    path('profile/<int:pk>', views.ShowProfile.as_view(), name='profile'),
    path('modifica/<int:pk>', views.ModifyUser.as_view(), name='modifica_user'),
    path('modificaPassword', views.PasswordChangeView, name='modica_password'),
    path('gallery', views.gallery, name='gallery'),
    path('logout', auth_views.LogoutView.as_view(), name='logout'),
    path('corsi', views.corsi, name='corsi'),
    path('corsi/<int:id>', views.corso_info, name='corso_info'),
    path('registrazione', views.SignUp.as_view(), name='registrazione'),
    path('login', auth_views.LoginView.as_view(), name='login'),
    path('check_username_unique', views.check_username_is_unique, name='check-username-unique'),
    re_path(r'^$', RedirectView.as_view(url='homepage', permanent=False), name='index'),
]

EnerGym_folder/forum/models.py
from django.db import models

from gestione_palestra.models import GymUser


class Topic_lezione(models.Model):
    titolo = models.CharField(max_length=40)
    descrizione = models.TextField(max_length=999)
    gymuser_topic = models.ForeignKey(GymUser, on_delete=models.PROTECT, related_name='gymuser_topic')
    creato = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'Topic-Lezioni'
        ordering = ['creato']

    def __str__(self):
        return self.titolo


class Commento(models.Model):
    topic = models.ForeignKey(Topic_lezione, on_delete=models.CASCADE, related_name='topic')
    gymuser_lezione = models.ForeignKey(GymUser, on_delete=models.PROTECT, related_name='gymuser_lezione')
    creato = models.DateTimeField(auto_now_add=True)
    testo = models.TextField(max_length=300)

    class Meta:
        verbose_name_plural = 'Commenti'

    def __str__(self):
        return 'Comment {} by {} in topic {}'.format(self.id, self.gymuser_lezione, self.topic_id)

EnerGym_folder/forum/forms.py
from django import forms

from forum import models
from forum.models import Commento, Topic_lezione


class CommentoForm(forms.ModelForm):

    class Meta:
        model = Commento
        fields = ('testo',)
        widgets = {
            'topic': forms.HiddenInput(),
            'gymuser_lezione': forms.HiddenInput(),
        }


class TopicForm(forms.ModelForm):

    class Meta:
        model = Topic_lezione
        fields = ('titolo', 'descrizione')
        widgets = {
            'gymuser_topic': forms.HiddenInput(),
        }

EnerGym_folder/forum/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404
from django.template.loader import render_to_string
from django.db.models import Q
from forum.forms import CommentoForm, TopicForm
from forum.models import Topic_lezione, Commento


@login_required()
def forum_homepage(request):

    topics = Topic_lezione.objects.all().order_by('-creato')
    query = request.GET.get('q')
    if query:
        topics = topics.filter(
            Q(titolo__icontains=query)|
            Q(descrizione__icontains=query)|
            Q(gymuser_topic__username__icontains=query)
        ).distinct()

    paginator = Paginator(topics, 5)
    page_request_var = "page"
    page = request.GET.get(page_request_var)

    try:
        topics = paginator.page(page)
    except PageNotAnInteger:
        topics = paginator.page(1)
    except EmptyPage:
        topics = paginator.page(paginator.num_pages)

    context = {
        'topics': topics,
        'page_request_var': page_request_var,
    }

    return render(request, 'forum/forum.html', context)


@login_required()
def topic(request, id):
    topic = Topic_lezione.objects.get(id=id)
    commenti = Commento.objects.filter(topic=topic)
    form = CommentoForm(request.POST or None)

    return render(request, 'forum/topic.html', {'topic': topic, 'commenti': commenti, 'form': form})


@login_required()
def save_commento(request, form, template_name, topic):
    data = dict()
    if request.method == 'POST':
        if form.is_valid():
            nuovo_commento_form = form.save(commit=False)
            nuovo_commento_form.gymuser_lezione = request.user
            nuovo_commento_form.topic = topic
            nuovo_commento_form.save()
            data['form_is_valid'] = True
            context = {'form': nuovo_commento_form}
        else:
            data['form_is_valid'] = False
            context = {'form': form}
    else:
        context = {'form': form}
    data['html_form'] = render_to_string(template_name, context, request=request)
    return JsonResponse(data)


@login_required
def crea_commento(request):

    if request.method == 'POST':
        topic_id = request.POST.get('id')
        topic = Topic_lezione.objects.get(id=topic_id)
        form = CommentoForm(data=request.POST)
    else:
        topic_id = request.GET.get('id')
        topic = Topic_lezione.objects.get(id=topic_id)
        form = CommentoForm()

    return save_commento(request, form, 'forum/crea_commento.html', topic)


@login_required
def update_commento(request, pk):

    commento = get_object_or_404(Commento, pk=pk)

    if request.method == 'POST':
        topic_id = request.POST.get('id')
        topic = Topic_lezione.objects.get(id=topic_id)
        form = CommentoForm(request.POST, instance=commento)
    else:
        topic_id = request.GET.get('id')
        topic = Topic_lezione.objects.get(id=topic_id)
        form = CommentoForm(instance=commento)

    return save_commento(request, form, 'forum/update_commento.html', topic)


@login_required
def delete_commento(request, pk):
    commento = get_object_or_404(Commento, pk=pk)
    data = dict()
    if request.method == 'POST':
        commento.delete()
        data['form_is_valid'] = True
    else:
        context = {'commento': commento}
        data['html_form'] = render_to_string(
            'forum/delete_commento.html',
            context,
            request=request
        )
    return JsonResponse(data)


@login_required
def add_topic(request):
    data = dict()

    if request.method == 'POST':
        form = TopicForm(request.POST)
        if form.is_valid():
            form_partial = form.save(commit=False)
            form_partial.gymuser_topic = request.user
            form_partial.save()
            form = form_partial
            data['form_is_valid'] = True
        else:
            data['form_is_valid'] = False
    else:
        form = TopicForm()

    context = {'form': form}
    data['html_form'] = render_to_string(
        'forum/crea_topic.html',
        context,
        request=request
    )
    return JsonResponse(data)


@login_required
def delete_topic(request, pk):
    topic = get_object_or_404(Topic_lezione, pk=pk)
    data = dict()

    if request.method == 'POST':
        topic.delete()
        data['form_is_valid'] = True
    else:
        context = {'topic': topic}
        data['html_form'] = render_to_string('forum/delete_topic.html', context, request=request)

    return JsonResponse(data)

EnerGym_folder/forum/templates/forum/crea_commento.html
<form method="post" action="{% url 'forum:crea_commento' %}" class="crea-commento-form">
    {% csrf_token %}
    <div class="modal-header">
        <h6 class="modal-title">Rispondi</h6>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <div class="modal-body">
        {{ form.testo }}
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Chiudi</button>
        <button type="submit" class="btn btn-primary">Crea</button>
    </div>
</form>

EnerGym_folder/forum/templates/forum/crea_topic.html
{% load crispy_forms_filters %}

<form method="post" action="{% url 'forum:add_topic' %}" class="crea-topic-form">
    {% csrf_token %}
    <div class="modal-header">
        <h6 class="modal-title">Nuova discussione</h6>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <div class="modal-body">
        {{ form.as_p }}
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Chiudi</button>
        <button type="submit" class="btn btn-primary">Crea</button>
    </div>
</form>

EnerGym_folder/forum/templates/forum/delete_commento.html
<form method="post" action="{% url 'forum:delete_commento' commento.id %}" class="delete-commento-form">
    {% csrf_token %}
    <div class="modal-header">
        <h6 class="modal-title">Vuoi eliminare il commento?</h6>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <div class="modal-body">
        <p class="lead">Sei sicuro di voler eliminare il commento?</p>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Chiudi</button>
        <button type="submit" class="btn btn-danger">Elimina</button>
    </div>
</form>

EnerGym_folder/forum/templates/forum/delete_topic.html
<form method="post" action="{% url 'forum:delete_topic' topic.id %}" class="delete-topic-form">
    {% csrf_token %}
    <div class="modal-header">
        <h4 class="modal-title">Vuoi eliminare il Topic?</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <div class="modal-body">
        <p class="lead">Sei sicuro di voler eliminare la discussione?</p>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Chiudi</button>
        <button type="submit" class="btn btn-danger">Rimuovi</button>
    </div>
</form>

EnerGym_folder/forum/templates/forum/forum.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Forum{% endblock %}

{% block style %}
    <style>
        body {
            background-image: url('{% static 'img/img5.jpg' %}');
            -webkit-background-size: cover;
            -moz-background-size: cover;
            -o-background-size: cover;
            background-size: cover;
        }

        .card:hover {
            -ms-transform: scale(1.05);
            -webkit-transform: scale(1.05);
            transform: scale(1.05);
        }

        .img{
            height: 60px;
            width: 60px;
            object-fit: cover;
            border-radius: 50%;
        }

        .card-body{
            position:relative;
        }

        .buttons{
            position: absolute;
            top: 10px;
            right: 10px;
        }

        div.flex-box{
            display: flex;
            justify-content: space-between;
            padding-right: 15px!important;
            padding-left: 15px!important;
            margin-bottom: 10px!important;
        }


    </style>
{% endblock %}

{% block body %}
    <div class="main">
        <div class="flex-box" id="div_btn">
            <span>
                <button type="button" class="btn btn-secondary crea-topic my_btn" data-url="{% url 'forum:add_topic' %}">Crea una nuova discussione <i class="fas fa-plus"></i></button>
            </span>
            <span>
                <form class="form-inline" method="GET" action="">
                    <input class="form-control" type="text" name="q" id="myInput" value="{{ request.GET.q }}" aria-label="Search" placeholder="Cerca discussioni..."/>
                    <input class="btn btn-success" type="submit" value="Cerca"/>
                </form>
            </span>
        </div>
        {% for topic in topics %}
            <div class="container-fluid mt-100" >
                <div class="row">
                    <div class="col-md-12">
                        <div class="card mb-4">
                            <div class="card-header">
                                <div class="media flex-wrap wx100 align-items-center">
                                    {% if topic.gymuser_topic.profile_img %}
                                        <img src="{{ topic.gymuser_topic.profile_img.url }}" class="img d-block ui-w-40 rounded-circle" >
                                    {% endif %}
                                    <div class="media-body ml-3"> <span data-abc="true">by {{ topic.gymuser_topic.username }}</span>
                                        <div class="text-muted small">{{ topic.creato }}</div>
                                    </div>
                                    <div id="titolo" class="card-body">
                                        <p>"<b>{{ topic.titolo }}</b>"</p>
                                        <span class="buttons">
                                                    {% if user.id == topic.gymuser_topic.id %}
                                                        <button data-url="{% url 'forum:delete_topic' topic.id %}" class="btn btn-danger delete-topic">elimina</button>
                                                    {% endif %}
                                            <a href="{% url 'forum:topic_info' topic.id %}" class="btn btn-primary my_btn">Vai alla discussione</a>
                                        </span>
                                    </div>
                                </div>
                            </div>
                            <div class="card-text">
                                <p id="descrizione-topic">{{ topic.descrizione }}</p>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        {% endfor %}
        <div class="pagination">
            <span class="step-links">
                {% if topics.has_previous %}
                    <a href="?{{ page_request_var}}={{ topics.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">Prec.</a>
                {% endif %}
                <span class="current">
                    Pagina {{ topics.number }} di {{ topics.paginator.num_pages }}
                </span>
                {% if topics.has_next %}
                    <a href="?{{ page_request_var}}={{ topics.next_page_number}}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">Succ.</a>
                {% endif %}
            </span>
        </div>
        <div class="modal fade" id="modal-topic">
            <div class="modal-dialog">
                <div class="modal-content">
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block script %}
    <script>
        $(function () {
            var loadForm = function () {
                var btn = $(this);
                $.ajax({
                    url: btn.attr("data-url"),
                    type: 'get',
                    dataType: 'json',
                    beforeSend: function () {
                        $("#modal-topic .modal-content").html("");
                        $("#modal-topic").modal("show");
                    },
                    success: function (data) {
                        $("#modal-topic .modal-content").html(data.html_form);
                    }
                });
            };

            var saveForm = function () {
                var form = $(this);
                $.ajax({
                    url: form.attr("action"),
                    data: form.serialize(),
                    type: form.attr("method"),
                    dataType: 'json',
                    success: function (data) {
                        if (data.form_is_valid) {
                            location.reload()
                        } else {
                            $("#modal-topic .modal-content").html(data.html_form);
                        }
                    }
                });
                return false;
            };

            // Crea topic
            $(".crea-topic").click(loadForm);
            $("#modal-topic").on("submit", ".crea-topic-form", saveForm);

            // Delete topic
            $(".delete-topic").click(loadForm);
            $("#modal-topic").on("submit", ".delete-topic-form", saveForm);
        });

    </script>
{% endblock %}

EnerGym_folder/forum/templates/forum/topic.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}
{% load static %}
{% block title %}{{ topic.titolo }}{% endblock %}

{% block style %}
    <style>
        body {
            background-image: url('{% static 'img/img9.jpg' %}');
            -webkit-background-size: cover;
            -moz-background-size: cover;
            -o-background-size: cover;
            background-size: cover;
        }

        .img{
            height: 60px;
            width: 60px;
            object-fit: cover;
            border-radius: 50%;
        }

        .card-body{
            position:relative;
        }

        .buttons{
            position: absolute;
            top: 10px;
            right: 10px;
        }
    </style>
{% endblock %}

{% block body %}

    <div class="main">
        <a href="{% url 'forum:forum_home' %}" class="btn btn-primary my_btn">Torna al forum</a>
        <br>
        <br>
        <div class="row">
            <div class="col-md-12">
                <div class="card mb-4">
                    <div class="card-header">
                        <div class="media flex-wrap w-100 align-items-center">
                            {% if topic.gymuser_topic.profile_img %}
                                <img src="{{ topic.gymuser_topic.profile_img.url }}" class="img d-block ui-w-40 rounded-circle" >
                            {% endif %}
                            <div class="media-body ml-3">
                                {% if topic.gymuser_topic.is_insegnante %}
                                    <span data-abc="true">by <a href="{% url "gestione_palestra:insegnante_info" topic.gymuser_topic.pk %}">{{ topic.gymuser_topic.username }}</a></span>
                                    <h6><span class="badge badge-success">Staff</span></h6>
                                {% else %}
                                    <span data-abc="true">by {{ topic.gymuser_topic.username }}</span>
                                {% endif %}
                                <div class="text-muted small">{{ topic.creato }}</div>
                            </div>
                            <div id="titolo" class="card-body">
                                <p>"<b>{{ topic.titolo }}</b>"</p>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <p>{{ topic.descrizione }}</p>
                    </div>
                </div>
            </div>
        </div>
        {% for commento in commenti %}
            <div class="row">
                <div class="col-md-12">
                    <div class="card" style="padding: 0px">
                        <div class="container-fluid" style="padding: 0px">
                            <div class="card-header col-sm-2" style="float: left">
                                <div class="media flex-wrap w-100 align-items-center">
                                    {% if commento.gymuser_lezione.profile_img %}
                                        <img src="{{ commento.gymuser_lezione.profile_img.url }}" class="img d-block ui-w-40 rounded-circle" >
                                    {% endif %}
                                </div>
                                <div class="media-body">
                                    {% if commento.gymuser_lezione.is_insegnante %}
                                        <span data-abc="true">by <a href="{% url "gestione_palestra:insegnante_info" commento.gymuser_lezione.pk %}">{{ commento.gymuser_lezione.username }}</a></span>
                                        <h6><span class="badge badge-success">Staff</span></h6>
                                    {% else %}
                                        <span data-abc="true">by {{ commento.gymuser_lezione.username }}</span>
                                    {% endif %}
                                    <div class="text-muted small">{{ commento.creato }}</div>
                                </div>
                            </div>
                            <div class="card-body col-sm-10" style="float: left">
                                <span>{{ commento.testo }}</span>
                                {% if user.id == commento.gymuser_lezione.id %}
                                    <span class="buttons">
                                                <button style="text-decoration: none; color:orange" class="delete-commento" type="button" data-url="{% url 'forum:delete_commento' commento.pk %}"><i class="fas fa-window-close"></i></button>
                                                <button style="text-decoration: none; color:orange" class="update-commento" type="button" data-url="{% url 'forum:update_commento' commento.pk %}"><i class="fas fa-edit"></i></button>
                                            </span>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
        <br>
        <button type="button" class="btn btn-primary crea-commento my_btn" style="margin-right: auto" data-url="{% url 'forum:crea_commento' %}">
            Commenta
        </button>
        <div class="modal fade" id="modal-commento">
            <div class="modal-dialog">
                <div class="modal-content">
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block script %}
    <script>
        $(function () {
            var loadForm = function () {
                var btn = $(this);
                $.ajax({
                    url: btn.attr("data-url"),
                    type: 'get',
                    data: {
                        'id' : {{ topic.id }}
                    },
                    dataType: 'json',
                    beforeSend: function () {
                        $("#modal-commento .modal-content").html("");
                        $("#modal-commento").modal("show");
                    },
                    success: function (data) {
                        $("#modal-commento .modal-content").html(data.html_form);
                    }
                });
            };

            var saveForm = function () {
                var form = $(this);
                var data = form.serializeArray();
                data.push({name: "id", value: {{topic.id}}});
                $.ajax({
                    url: form.attr("action"),
                    data: data,
                    type: form.attr("method"),
                    dataType: 'json',
                    success: function (data) {
                        if (data.form_is_valid) {
                            location.reload()
                        }
                        else {
                            $("#modal-commento .modal-content").html(data.html_form);
                        }
                    }
                });
                return false;
            };


            // Crea commento
            $(".crea-commento").click(loadForm);
            $("#modal-commento").on("submit", ".crea-commento-form", saveForm);

            // Update commento
            $(".delete-commento").click(loadForm);
            $("#modal-commento").on("submit", ".update-commento-form", saveForm);

            //Delete commento
            $(".update-commento").click(loadForm);
            $("#modal-commento").on("submit", ".delete-commento-form", saveForm);
        });
    </script>
{% endblock %}

EnerGym_folder/forum/templates/forum/update_commento.html
{% load widget_tweaks %}
<form method="post" action="{% url 'forum:update_commento' form.instance.pk %}" class="update-commento-form">
    {% csrf_token %}
    <div class="modal-header">
        <h6 class="modal-title">Modifica commento</h6>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <div class="modal-body">
        {% for field in form %}
            <div class="form-group{% if field.errors %} has-error{% endif %}">
                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                {% render_field field class="form-control" %}
                {% for error in field.errors %}
                    <p class="help-block">{{ error }}</p>
                {% endfor %}
            </div>
        {% endfor %}
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Chiudi</button>
        <button type="submit" class="btn btn-primary" value="Refresh Page" onclick="window.location.reload();">Aggiorna</button>
    </div>
</form>