EnerGym_folder/EnerGym/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, re_path, include
from django.views.generic.base import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('EnerGym/', include('gestione_palestra.urls')),
    path('EnerGym/', include('lezioni.urls')),
    path('EnerGym/', include('forum.urls')),
    re_path(r'^$', RedirectView.as_view(url='EnerGym', permanent=False), name='index')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

EnerGym_folder/forum/urls.py
from django.contrib.staticfiles.storage import staticfiles_storage
from django.urls import path
from django.urls import re_path
from django.views.generic import RedirectView
from . import views

app_name = 'forum'

urlpatterns = [
    path('forum', views.forum_homepage, name='forum_home'),
    path('forum/topic/<int:id>', views.topic, name='topic_info'),
    path('forum/topic/add_comment', views.crea_commento, name='crea_commento'),
    path('forum/topic/update_commento/<int:pk>', views.update_commento, name='update_commento'),
    path('forum/topic/delete_commento/<int:pk>', views.delete_commento, name='delete_commento'),
    path('forum/topic/add_topic', views.add_topic, name='add_topic'),
    path('forum/topic/delete_topic/<int:pk>', views.delete_topic, name='delete_topic'),
    path('favicon.ico', RedirectView.as_view(url=staticfiles_storage.url('img/Energym.ico'))),
    re_path(r'^$', RedirectView.as_view(url='homepage', permanent=False), name='index'),
]

EnerGym_folder/gestione_palestra/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.urls import re_path
from django.contrib.auth import views as auth_views
from django.views.generic.base import RedirectView

from . import views

app_name = 'gestione_palestra'

urlpatterns = [
    path('homepage', views.homepage, name='homepage'),
    path('insegnanti', views.istruttori, name='insegnanti'),
    path('insegnanti/<int:id>', views.istruttore_info, name='insegnante_info'),
    path('contatti', views.contatti, name='contatti'),
    path('notizie/<int:id>', views.notizia_info, name='notizia_info'),
    path('notizie', views.notizie, name='notizie'),
    path('profile/<int:pk>', views.ShowProfile.as_view(), name='profile'),
    path('modifica/<int:pk>', views.ModifyUser.as_view(), name='modifica_user'),
    path('modificaPassword', views.PasswordChangeView, name='modica_password'),
    path('gallery', views.gallery, name='gallery'),
    path('logout', auth_views.LogoutView.as_view(), name='logout'),
    path('corsi', views.corsi, name='corsi'),
    path('corsi/<int:id>', views.corso_info, name='corso_info'),
    path('registrazione', views.SignUp.as_view(), name='registrazione'),
    path('login', auth_views.LoginView.as_view(), name='login'),
    path('check_username_unique', views.check_username_is_unique, name='check-username-unique'),
    re_path(r'^$', RedirectView.as_view(url='homepage', permanent=False), name='index'),
]

EnerGym_folder/gestione_palestra/models.py
from django.contrib.auth.models import AbstractUser, User
from django.db import models
from django.template.defaultfilters import register


class GymUser(AbstractUser):
    profile_img = models.ImageField(upload_to='users_profile_img', default="profile_img.png")
    is_insegnante = models.BooleanField(default=False)
    descrizione_per_insegnante = models.TextField(max_length=400, blank=True)

    class Meta:
        verbose_name_plural = 'GymUser'

    def __str__(self):
        return self.first_name + ' ' + self.last_name

    @register.filter
    def return_corsi(self):
        id_corsi_insegnante = InsegnanteCorso.objects.filter(insegnante_id=self.id).values_list('corso_id', flat=True)
        corsi = Corso.objects.filter(id__in=id_corsi_insegnante)

        return corsi



class Corso(models.Model):
    nome = models.CharField(max_length=40)
    descrizione = models.TextField(max_length=400)

    class Meta:
        verbose_name_plural = 'Corsi'

    def __str__(self):
        return self.nome


class InsegnanteCorso(models.Model):
    corso = models.ForeignKey(Corso, on_delete=models.PROTECT, related_name='corso')
    insegnante = models.ForeignKey(GymUser, on_delete=models.PROTECT, related_name='insegnante')

    class Meta:
        verbose_name_plural = 'Insegnante-Corso'
        unique_together = ("corso", "insegnante")

    def __str__(self):
        return 'Corso: ' + self.corso.nome + ' - Insegnante: ' + self.insegnante.first_name + ' ' + self.insegnante.last_name

    def return_corso(self):
        return self.corso.nome


class Notizia(models.Model):
    titolo = models.CharField(max_length=40)
    descrizione = models.TextField(max_length=999)
    data_creazione = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'Notizie'

    def __str__(self):
        return self.titolo


class Gallery(models.Model):
    photo_path = models.ImageField(upload_to='gallery')

    def __str__(self):
        immagine = str(self.photo_path)
        return immagine

    class Meta:
        verbose_name_plural = 'ImmaginiGallery'

EnerGym_folder/gestione_palestra/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm
from django import forms
from gestione_palestra.models import GymUser, InsegnanteCorso


class SignUpForm(UserCreationForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['first_name'].widget.attrs['placeholder'] = 'Nome'
        self.fields['last_name'].widget.attrs['placeholder'] = 'Cognome'
        self.fields['username'].widget.attrs['placeholder'] = 'Username'
        self.fields['email'].widget.attrs['placeholder'] = 'esempio@esempio.com'
        self.fields['password1'].widget.attrs['placeholder'] = 'Immetti una password'
        self.fields['password2'].widget.attrs['placeholder'] = 'Ripeti la password'
        self.helper = FormHelper()
        self.helper.add_input(
            Submit('submit', 'Registrati', css_class='btn btn-success')
        )

    class Meta:
        model = GymUser
        fields = (
            'first_name',
            'last_name',
            'username',
            'email',
            'password1',
            'password2',
            'profile_img'
        )

    def clean_first_name(self):
        return self.cleaned_data['first_name'].capitalize()

    def clean_last_name(self):
        return self.cleaned_data['last_name'].capitalize()


class ModifyUserForm(forms.ModelForm):
    helper = FormHelper()
    helper.form_id = 'modify_user_form'
    helper.form_method = 'POST'
    helper.add_input(Submit('submit', 'Salva'))

    class Meta:
        model = GymUser
        fields = ('first_name', 'last_name', 'username', 'email', 'descrizione_per_insegnante', 'profile_img')

    def clean_first_name(self):
        return self.cleaned_data['first_name'].capitalize()

    def clean_last_name(self):
        return self.cleaned_data['last_name'].capitalize()


class PasswordChange(PasswordChangeForm):
    helper = FormHelper()
    helper.form_id = 'add_test_form'
    helper.form_method = 'POST'
    helper.add_input(Submit('submit', 'Modifica password'))


class InsegnanteCorsoForm(forms.ModelForm):
    class Meta:
        model = InsegnanteCorso
        fields = ('corso', 'insegnante')

    def __init__(self, *args, **kwargs):
        super(InsegnanteCorsoForm, self).__init__(*args, **kwargs)
        insegnanti = GymUser.objects.filter(is_insegnante=True)
        self.fields['insegnante'].queryset = insegnanti

EnerGym_folder/gestione_palestra/views.py
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.http import JsonResponse
from django.urls import reverse_lazy
from django.views.generic import CreateView, DetailView, UpdateView
from django.shortcuts import render, redirect
from gestione_palestra.forms import SignUpForm, PasswordChange, ModifyUserForm
from gestione_palestra.models import Corso, Notizia, Gallery, GymUser
from lezioni.models import Prenotazione


def homepage(request):
    notizie = Notizia.objects.all().order_by('-data_creazione')[:6]
    notizie_consigliate = None

    if request.user.is_authenticated:
        user = request.user
        lezioni_utente = Prenotazione.objects.filter(user_id=user.id).values_list('lezione__insegnantecorso__corso__nome', flat=True).distinct()

        data = set()

        for nome_corso in lezioni_utente:
            data.add((Notizia.objects.filter(titolo__contains=nome_corso).order_by('data_creazione').values('id')[:1]))

        notizie_consigliate = Notizia.objects.filter(pk__in=data).order_by('-data_creazione')[:3]

    return render(request, 'gestione_palestra/homepage.html', {'notizie': notizie, 'notizie_consigliate': notizie_consigliate})


class SignUp(CreateView):
    model = GymUser
    form_class = SignUpForm
    template_name = 'registration/registrazione.html'
    success_url = reverse_lazy('gestione_palestra:homepage')

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'cliente'
        return super().get_context_data(**kwargs)


def istruttori(request):
    ins = GymUser.objects.filter(is_insegnante=True)
    return render(request, 'gestione_palestra/insegnanti.html', {'insegnanti': ins})


def istruttore_info(request, id):
    ins = GymUser.objects.get(id=id)
    corsi = ins.return_corsi
    return render(request, 'gestione_palestra/insegnante_info.html', {'insegnante': ins, 'corsi':corsi})


def corsi(request):
    return render(request, 'gestione_palestra/corsi.html')


def corso_info(request, id):
    corso = Corso.objects.get(id=id)
    return render(request, 'gestione_palestra/corso_info.html', {'corso': corso})


def check_username_is_unique(request):
    user = None
    username = request.GET.get('username', False)
    if username:
        user = User.objects.filter(username=username)
    return JsonResponse({'is_not_unique': True if user else False})


def contatti(request):
    return render(request, 'gestione_palestra/contatti.html')


def gallery(request):
    photos = Gallery.objects.all()
    return render(request, 'gestione_palestra/gallery.html', {'photos': photos})


def notizia_info(request, id):
    news = Notizia.objects.get(id=id)
    return render(request, 'gestione_palestra/notizia.html', {'news': news})


class ShowProfile(LoginRequiredMixin, DetailView):
    model = GymUser
    template_name = 'gestione_palestra/profile.html'


class ModifyUser(LoginRequiredMixin, UpdateView):
    model = GymUser
    template_name = 'gestione_palestra/modificauser.html'
    form_class = ModifyUserForm
    success_url = reverse_lazy('gestione_palestra:profile')

    def get_success_url(self):
        user_id = self.kwargs['pk']
        return reverse_lazy('gestione_palestra:profile', kwargs={'pk': user_id})


@login_required()
def PasswordChangeView(request):
    if request.method == 'POST':
        form = PasswordChange(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            return redirect('gestione_palestra:profile', pk=request.user.id)
    else:
        form = PasswordChange(request.user)
    return render(request, 'gestione_palestra/password_change.html', {'form': form})


def notizie(request):
    notizie = Notizia.objects.all().order_by('-data_creazione')
    return render(request, 'gestione_palestra/notizie.html', {'notizie': notizie})

EnerGym_folder/gestione_palestra/templates/gestione_palestra/contatti.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Contatti{% endblock %}

{% block style %}
    <style>
        body {
            background-image: url('{% static 'img/img8.jpg' %}');
            -webkit-background-size: cover;
            -moz-background-size: cover;
            -o-background-size: cover;
            background-size: cover;
        }
    </style>
{% endblock %}

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-xl-6 col-lg-4 col-xl-4 py-2">
                <div class="card h-100">
                    <div class="card-info">
                        <h4 class="card-title">{{'Contattaci:'}}</h4>
                        <ul>
                            <li>Email: info@energym.com</li>
                            <li>Tel: 059/909012</li>
                            <li>Cellulare: 345/7685990</li>
                            <div align="right">
                                <a type="button" class="btn btn-secondary my_btn" href="{% url 'gestione_palestra:homepage' %}">Indietro</a>
                            </div>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

EnerGym_folder/gestione_palestra/templates/gestione_palestra/corsi.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Corsi{% endblock %}

{% block style %}
    <style>
        body {
            background-image: url('{% static 'img/img4.jpg' %}');
            -webkit-background-size: cover;
            -moz-background-size: cover;
            -o-background-size: cover;
            background-size: cover;
        }
        .card:hover {
            -ms-transform: scale(1.1);
            -webkit-transform: scale(1.1);
            transform: scale(1.1);
        }
    </style>
{% endblock %}

{% block body %}
    <div class="container">
        <div class="row" style="padding: 20px">
            {% for corso in Corsi %}
                <div class="col-md-6 col-lg-4 col-xl-4 py-2">
                    <div class="card h-100">
                        <div class="card-info">
                            <h4 class="card-title">{{corso.nome}}</h4>
                            <div class="card-img-container">

                            </div>
                            <p class="card-text">{{corso.descrizione}}</p>
                        </div>
                        <div class="card-button">
                            <a href="{% url 'gestione_palestra:corso_info' corso.id %}" class="btn btn-primary my_btn">Vai alla pagina dedicata a {{ corso.nome }}</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

EnerGym_folder/gestione_palestra/templates/gestione_palestra/corso_info.html
{% extends 'base.html' %}
{% load static %}
{% block title %}{{ corso.nome }}{% endblock %}

{% block style %}
    <style>
        body {
            background-image: url('{% static 'img/img4.jpg' %}');
            -webkit-background-size: cover;
            -moz-background-size: cover;
            -o-background-size: cover;
            background-size: cover;
        }
    </style>
{% endblock %}

{% block body %}
    <div class="main">
        <h4>{{corso.nome}}</h4>
        <p>{{corso.descrizione}}</p>
        <div align="right">
            <a href="{% url 'gestione_palestra:corsi' %}" class="btn btn-primary my_btn">Torna ai corsi</a>
        </div>
    </div>
{% endblock %}

EnerGym_folder/gestione_palestra/templates/gestione_palestra/gallery.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Gallery{% endblock %}

{% block style %}
    <style>
        body {
            background: url('{% static 'img/img2.jpg' %}');
            -webkit-background-size: cover;
            -moz-background-size: cover;
            -o-background-size: cover;
            background-size: cover;
        }

         #img img {
            max-width: 100%;
            max-height: 100%;
        }

    </style>
{% endblock %}

{% block body %}
    <div class="container">
        <div class="row" style="padding-top: 20px; align-items: center">
            {% for photo in photos %}
                <div class="col-md-3 col-lg-4 col-xl-4 py-2">
                    <div id="img">
                        <img src="{{ photo.photo_path.url }}" />
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

EnerGym_folder/gestione_palestra/templates/gestione_palestra/homepage.html
{% extends 'base.html' %}
{% load static %}
{% block title %}ENERGYMfitness{% endblock %}

{% block style %}
    <style>
        body {
            background-image: url('{% static 'img/img1.jpg' %}');
            -webkit-background-size: cover;
            -moz-background-size: cover;
            -o-background-size: cover;
            background-size: cover;
        }

        #benvenuto {
            background-color: orange;
            margin-top: 10px;
            margin-bottom: 5px;
            border-radius: 5px;
        }

        #benvenuto p {
            text-align: center;
            font-size: 30px;
            color: white;
            margin: 0;
            font-family: Calibri;
        }

        #title{
            background-color: rgba(253,126,20, 0.8);
            color: white;
            border-radius: 5px;
        }
    </style>
{% endblock %}

{% block body %}
    <div class="container">
        <div id="benvenuto">
            {% if user.is_authenticated %}
                <p>Benvenuto, <b>{{ user.get_username }}!</b></p>
            {% else %}
                <p>Benvenuto!</p>
                <p style="font-size: 15px;">Entra nella nostra community!</p>
            {% endif %}
        </div>

        {% if notizie_consigliate %}
            <div id="title">
                <p style="text-align: center; margin-bottom: 10px"><b>Notizie che potrebbero interessarti</b></p>
            </div>
        {% elif user.is_authenticated %}
            <div id="title">
                <p style="text-align: center;font-size: 10px; font-family: Bahnschrift; margin-bottom: 10px"><b>Non ci sono notizie consigliate per te</b></p>
            </div>
        {% endif %}
        <div class="row">
            {% for news in notizie_consigliate %}
                <div class="col-md-6 col-lg-4 col-xl-4 py-2">
                    <div class="card h-100">
                        <div class="card-info">
                            <h6><span class="badge badge-success">Per te</span></h6>
                            <h4 class="card-title">{{news.titolo}}</h4>
                            <p class="card-text">{{news.descrizione}}</p>
                        </div>
                        <div class="text-muted small">{{ news.data_creazione }}</div>
                        <div class="card-button">
                            <a href="{% url 'gestione_palestra:notizia_info' news.id %}" class="btn btn-primary my_btn">Dimmi di più</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        {% if notizie %}
            <div id="title">
                <p style="text-align: center; margin-bottom: 0px"><b>Ultime notizie</b></p>
            </div>
        {% endif %}

        <div class="row">
            {% if user.is_authenticated %}
                {% for news in notizie %}
                    {% if news not in notizie_consigliate %}
                        <div class="col-md-6 col-lg-4 col-xl-4 py-2">
                            <div class="card h-100">
                                <div class="card-info">
                                    <h4 class="card-title">{{news.titolo}}</h4>
                                    <div class="card-img-container">
                                    </div>
                                    <p class="card-text">{{news.descrizione}}</p>
                                </div>
                                <div class="text-muted small">{{ news.data_creazione }}</div>
                                <div class="card-button">
                                    <a href="{% url 'gestione_palestra:notizia_info' news.id %}" class="btn btn-primary my_btn">Dimmi di più</a>
                                </div>
                            </div>
                        </div>
                    {% endif %}
                {% empty %}
                    <div id="title" class="col-md-6 col-lg-4 col-xl-4 py-2">
                        <p style="text-align: center; margin-bottom: 0px"><b>Non ci sono notizie</b></p>
                    </div>
                {% endfor %}
            {% else %}
                {% for news in notizie %}
                    <div class="col-md-6 col-lg-4 col-xl-4 py-2">
                        <div class="card h-100">
                            <div class="card-info">
                                <h4 class="card-title">{{news.titolo}}</h4>
                                <div class="card-img-container">
                                </div>
                                <p class="card-text">{{news.descrizione}}</p>
                            </div>
                            <div class="text-muted small">{{ news.data_creazione }}</div>
                            <div class="card-button">
                                <a href="{% url 'gestione_palestra:notizia_info' news.id %}" class="btn btn-primary my_btn">Dimmi di più</a>
                            </div>
                        </div>
                    </div>
                {% empty %}
                    <div id="title">
                        <p style="text-align: center; margin-bottom: 0px"><b>Non ci sono notizie</b></p>
                    </div>
                {% endfor %}
            {% endif %}

        </div>
        <a href="{% url 'gestione_palestra:notizie' %}"  class="btn btn-primary my_btn">Tutte le news</a>
    </div>
{% endblock %}

EnerGym_folder/gestione_palestra/templates/gestione_palestra/insegnante_info.html
{% extends 'base.html' %}
{% load static %}
{% block title %}{{ corso.nome }}{% endblock %}
{% block style %}
    <style>
        body {
            background-image: url('{% static 'img/img4.jpg' %}');
            -webkit-background-size: cover;
            -moz-background-size: cover;
            -o-background-size: cover;
            background-size: cover;
        }
        .img{
            height: 180px;
            width: 180px;
            object-fit: cover;
            border-radius: 50%;
        }

        #descrizione{
            background-color: rgba(255,255,255, 0.7);
            border-radius: 10px;
        }

        #dati{
            background-color: rgba(255,255,255, 0.7);
            border-radius: 10px;
            padding: 5px;
        }
    </style>
{% endblock %}

{% block body %}
    <div class="main">
        <div>
            <h1 align="center" style="padding-bottom: 20px">{{insegnante.first_name}} {{insegnante.last_name}}</h1>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div>
                    <div class="container-fluid">
                        <div  class="col-sm-2" style="float: left">
                            <div id="dati">
                                <p><b>I miei corsi:</b></p>
                                <ul>
                                    {% for corso in corsi %}
                                        <li><p><a href="{% url 'gestione_palestra:corso_info' corso.id %}">{{ corso.nome }}</a></p></li>
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>
                        <div id="descrizione" class="col-sm-8" style="float: left">
                            <p><b>Qualcosa su di me:</b> {{ insegnante.descrizione_per_insegnante }}</p>
                            <p>Nome: <b>{{ insegnante.first_name }}</b></p>
                            <p>Cognome: <b>{{ insegnante.last_name }}</b></p>
                            <p>Username: <b>{{ insegnante.username }}</b></p>
                            <p>Email: {{ insegnante.email }}</p>
                        </div>
                        <div class="col-sm-2" style="float: left; text-align: center">
                            <img class="img" src="{{ insegnante.profile_img.url }}" />
                            <br>
                            <br>
                            <a type="button" class="btn btn-secondary my_btn" href="{% url 'gestione_palestra:insegnanti' %}">Indietro</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block script %}
{% endblock%}

EnerGym_folder/gestione_palestra/templates/gestione_palestra/insegnanti.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Istruttori{% endblock %}

{% block style %}
    <style>
        body {
            background-image: url('{% static 'img/img6.jpg' %}');
            -webkit-background-size: cover;
            -moz-background-size: cover;
            -o-background-size: cover;
            background-size: cover;
        }

        .card:hover {
            -ms-transform: scale(1.1);
            -webkit-transform: scale(1.1);
            transform: scale(1.1);
        }

        .img{
            height: 80px;
            width: 80px;
            object-fit: cover;
            border-radius: 50%;
        }

        .card-img-container {
            position: relative;
        }

        .card-img-container .img{
            position: relative;
            margin: auto;
        }
    </style>
{% endblock %}

{% block body %}
    <br>
    <br>
    <div class="container">
        <div class="row" style="padding: 20px">
            {% for insegnante in insegnanti %}
                <div class="col-md-6 col-lg-4 col-xl-4 py-2">
                    <div class="card h-100">
                        <div class="card-info">
                            <div class="card-img-container">
                                <img src="{{ insegnante.profile_img.url }}" class="img d-block ui-w-40 rounded-circle" >
                            </div>
                            <h4 class="card-title">{{insegnante.first_name}} {{insegnante.last_name}}</h4>
                            <p class="card-text">{{insegnante.descrizione_per_insegnante}}</p>
                        </div>
                        <div class="card-button">
                            <a href="{% url 'gestione_palestra:insegnante_info' insegnante.id %}" class="btn btn-primary my_btn">Vai alla pagina dedicata a {{ insegnante.first_name }}</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

EnerGym_folder/gestione_palestra/templates/gestione_palestra/notizia.html
{% extends 'base.html' %}
{% load static %}
{% block title %}{{ news.titolo }}{% endblock %}

{% block style %}
    <style>
        body {
            background-image: url('{% static 'img/img4.jpg' %}');
            -webkit-background-size: cover;
            -moz-background-size: cover;
            -o-background-size: cover;
            background-size: cover;
        }
    </style>
{% endblock %}

{% block body %}
    <div class="main">
        <h4>{{news}}</h4>
        <p>{{news.descrizione}}</p>
        <div align="right">
            <a type="button" class="btn btn-secondary my_btn" href="{% url 'gestione_palestra:homepage' %}">Indietro</a>
        </div>
    </div>
{% endblock %}

EnerGym_folder/gestione_palestra/templates/gestione_palestra/notizie.html
{% extends 'base.html' %}
{% load static %}
{% block title %}ENERGYMfitness{% endblock %}

{% block style %}
    <style>
        body {
            background-image: url('{% static 'img/img1.jpg' %}');
            -webkit-background-size: cover;
            -moz-background-size: cover;
            -o-background-size: cover;
            background-size: cover;
        }

        #benvenuto {
            background-color: orange;
            margin-top: 10px;
            margin-bottom: 5px;
            border-radius: 5px;
        }

        #benvenuto p {
            text-align: center;
            font-size: 30px;
            color: white;
            margin: 0;
            font-family: Calibri;
        }

        #title{
            background-color: rgba(253,126,20, 0.8);
            color: white;
            border-radius: 5px;
        }
    </style>
{% endblock %}

{% block body %}
    <div class="container">
        <div id="title">
            <p style="text-align: center; margin-bottom: 0px"><b>Tutte le news</b></p>
        </div>
        <div class="row">
            {% for news in notizie %}
                <div class="col-md-6 col-lg-4 col-xl-4 py-2">
                    <div class="card h-100">
                        <div class="card-info">
                            <h4 class="card-title">{{news.titolo}}</h4>
                            <div class="card-img-container">
                            </div>
                            <p class="card-text">{{news.descrizione}}</p>
                        </div>
                        <div class="text-muted small">{{ news.data_creazione }}</div>
                        <div class="card-button">
                            <a href="{% url 'gestione_palestra:notizia_info' news.id %}" class="btn btn-primary my_btn">Dimmi di più</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

EnerGym_folder/gestione_palestra/templates/gestione_palestra/profile.html
{% extends 'base.html'%}
{% load static %}
{% block title  %}Profilo di {{ object.username }}{% endblock %}
{% block style %}
    <style>
        body {
            background-image: url('{% static 'img/img4.jpg' %}');
            -webkit-background-size: cover;
            -moz-background-size: cover;
            -o-background-size: cover;
            background-size: cover;
        }
        .img{
            height: 100px;
            width: 100px;
            object-fit: cover;
            border-radius: 50%;
        }


    </style>
{% endblock %}

{% block body %}
    <div class="main">
        <div>
            <h1 align="center" style="padding-bottom: 20px">Gestione profilo</h1>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div>
                    <div class="container-fluid">
                        <div class="col-sm-2" style="float: left">
                            <div class="media flex-wrap w-100 align-items-center">
                                <img class="img" src="{{ object.profile_img.url }}" />
                            </div>
                        </div>
                        <div class="col-sm-10" style="float: left">
                            <p>Nome: <b>{{ object.first_name }}</b></p>
                            <p>Cognome: <b>{{ object.last_name }}</b></p>
                            <p>Username: <b>{{ object.username }}</b></p>
                            <p>Email: {{ object.email }}</p>
                            {% if user.is_insegnante %}
                                <p>Descrizione: {{ object.descrizione_per_insegnante }}</p>
                            {% endif %}
                            <br>
                            <a class="btn btn-success mr-5 my_btn"  href="{% url 'gestione_palestra:modifica_user' user.id %}">Modifica profilo</a>
                            <a class="btn btn-success my_btn"  href="#">Modifica password</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}