EnerGym_folder/EnerGym/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, re_path, include
from django.views.generic.base import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('EnerGym/', include('gestione_palestra.urls')),
    path('EnerGym/', include('lezioni.urls')),
    path('EnerGym/', include('forum.urls')),
    re_path(r'^$', RedirectView.as_view(url='EnerGym', permanent=False), name='index')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

EnerGym_folder/forum/urls.py
from django.contrib.staticfiles.storage import staticfiles_storage
from django.urls import path
from django.urls import re_path
from django.views.generic import RedirectView
from . import views

app_name = 'forum'

urlpatterns = [
    path('forum', views.forum_homepage, name='forum_home'),
    path('forum/topic/<int:id>', views.topic, name='topic_info'),
    path('forum/topic/add_comment', views.crea_commento, name='crea_commento'),
    path('forum/topic/update_commento/<int:pk>', views.update_commento, name='update_commento'),
    path('forum/topic/delete_commento/<int:pk>', views.delete_commento, name='delete_commento'),
    path('forum/topic/add_topic', views.add_topic, name='add_topic'),
    path('forum/topic/delete_topic/<int:pk>', views.delete_topic, name='delete_topic'),
    path('favicon.ico', RedirectView.as_view(url=staticfiles_storage.url('img/Energym.ico'))),
    re_path(r'^$', RedirectView.as_view(url='homepage', permanent=False), name='index'),
]

EnerGym_folder/gestione_palestra/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.urls import re_path
from django.contrib.auth import views as auth_views
from django.views.generic.base import RedirectView

from . import views

app_name = 'gestione_palestra'

urlpatterns = [
    path('homepage', views.homepage, name='homepage'),
    path('insegnanti', views.istruttori, name='insegnanti'),
    path('insegnanti/<int:id>', views.istruttore_info, name='insegnante_info'),
    path('contatti', views.contatti, name='contatti'),
    path('notizie/<int:id>', views.notizia_info, name='notizia_info'),
    path('notizie', views.notizie, name='notizie'),
    path('profile/<int:pk>', views.ShowProfile.as_view(), name='profile'),
    path('modifica/<int:pk>', views.ModifyUser.as_view(), name='modifica_user'),
    path('modificaPassword', views.PasswordChangeView, name='modica_password'),
    path('gallery', views.gallery, name='gallery'),
    path('logout', auth_views.LogoutView.as_view(), name='logout'),
    path('corsi', views.corsi, name='corsi'),
    path('corsi/<int:id>', views.corso_info, name='corso_info'),
    path('registrazione', views.SignUp.as_view(), name='registrazione'),
    path('login', auth_views.LoginView.as_view(), name='login'),
    path('check_username_unique', views.check_username_is_unique, name='check-username-unique'),
    re_path(r'^$', RedirectView.as_view(url='homepage', permanent=False), name='index'),
]

EnerGym_folder/lezioni/urls.py
from django.urls import re_path
from django.urls import path
from django.views.generic import RedirectView
from . import views

app_name = 'lezioni'

urlpatterns = [
    path('lezioni', views.lezioni, name='lezioni'),
    path('lezioni/le_mie_lezioni/<int:id>', views.gestione_lezioni, name='gestione_lezioni'),
    path('lezioni/crea', views.crea_lezione, name='crea_lezione'),
    path('lezioni/update/<int:pk>', views.update_lezione, name='update_lezione'),
    path('lezioni/delete/<int:pk>', views.delete_lezione, name='delete_lezione'),
    path('lezioni/prenotate/<int:id>', views.prenotazioni, name='prenotazioni'),
    path('lezioni/prenota', views.Prenota.as_view(), name='prenota'),
    path('lezioni/prenota/delete', views.DeletePrenotazione.as_view(), name='delete_prenotazione'),
    re_path(r'^$', RedirectView.as_view(url='homepage', permanent=False), name='index'),
]

EnerGym_folder/lezioni/models.py
from django.db import models
from django.utils import timezone

from gestione_palestra.models import Corso, GymUser, InsegnanteCorso


class Lezione(models.Model):
    insegnantecorso = models.ForeignKey(InsegnanteCorso, on_delete=models.PROTECT, related_name='insegnantecorso',
                                        null=True)
    descrizione = models.TextField(max_length=400)
    posti_disponibili_tot = models.PositiveIntegerField()
    data = models.DateTimeField()
    posti_finiti = models.BooleanField(default=False)

    class Meta:
        verbose_name_plural = 'Lezioni'

    def __str__(self):
        return self.insegnantecorso.insegnante.last_name + ' - ' + self.insegnantecorso.corso.nome + ' - ' + str(
            self.data)

    def return_posti_rimasti (self):
        posti_rimasti = self.posti_disponibili_tot - self.return_posti_occupati()
        if posti_rimasti < 1:
            self.posti_finiti = True
        else:
            self.posti_finiti = False
        return posti_rimasti

    def return_posti_occupati (self):
        posti_occupati = 0
        list = Prenotazione.objects.filter(lezione_id=self.id).values_list('lezione_id', flat=True)
        for x in list:
            if x == self.id:
                posti_occupati += 1
        return posti_occupati

    def non_disponibile(self):
        return self.data < timezone.now()


class Prenotazione(models.Model):
    user = models.ForeignKey(GymUser, on_delete=models.CASCADE)
    lezione = models.ForeignKey(Lezione, on_delete=models.CASCADE)

    class Meta:
        unique_together = ('user', 'lezione')
        verbose_name_plural = 'Prenotazioni'

    def __str__(self):
        return 'Lezione di {} del {} - prenotazione by [username]: {}'.format(self.lezione.insegnantecorso.corso.nome,
                                                                              self.lezione.data,
                                                                              self.user.username
                                                                              )

EnerGym_folder/lezioni/forms.py
from django import forms
from django.utils import timezone

from lezioni.models import Lezione

from gestione_palestra.models import InsegnanteCorso


class LezioneForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user')
        super().__init__(*args, **kwargs)
        queryset = InsegnanteCorso.objects.filter(insegnante_id=user)
        self.fields['insegnantecorso'] = forms.ModelChoiceField(queryset=queryset)
        self.fields['insegnantecorso'].label_from_instance = lambda obj: "%s" % obj.return_corso()
        self.fields['data'].widget.attrs['placeholder'] = 'yyyy-mm-dd hh:mm'

    class Meta:
        model = Lezione
        fields = ('insegnantecorso', 'descrizione', 'posti_disponibili_tot', 'data')

    def clean_data(self):
        data = self.cleaned_data.get('data')
        if data < timezone.now():
            raise forms.ValidationError("Inserire una data valida")
        return data

    def clean_posti_disponibili_tot(self):
        posti_disponibili_new = self.cleaned_data.get('posti_disponibili_tot')

        if posti_disponibili_new <= 0:
            raise forms.ValidationError("Inserire un valore maggiore di 0")

        if self.instance.posti_disponibili_tot is not None:
            lezione = Lezione.objects.get(id=self.instance.id)
            if lezione.return_posti_occupati() >= posti_disponibili_new:
                raise forms.ValidationError("Ci sono troppi utenti gà iscritti a questa lezione")

        return posti_disponibili_new

EnerGym_folder/lezioni/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404
from django.template.loader import render_to_string
from django.views.generic import DeleteView, TemplateView

from gestione_palestra.models import GymUser, Corso, InsegnanteCorso
from lezioni.decorators import insegnante_only
from lezioni.forms import LezioneForm
from lezioni.models import Lezione, Prenotazione


@login_required
def lezioni(request):
    prenot = Prenotazione.objects.filter(user_id=request.user.id).values_list('lezione_id', flat=True)
    lezioni_prenotate = Lezione.objects.filter(id__in=prenot)
    lezioni = Lezione.objects.all().order_by('-data')

    query = request.GET.get('q')
    if query:
        lezioni = lezioni.filter(
            Q(insegnantecorso__corso__nome__icontains=query)
        ).distinct()

    return render(request, 'lezioni/lezioni.html', {'lezioni': lezioni,
                                                    'lezioni_prenotate': lezioni_prenotate}
                  )


@insegnante_only
@login_required
def gestione_lezioni(request, id):
    id_corsi_insegnante = InsegnanteCorso.objects.filter(insegnante_id=id).values_list('corso_id', flat=True)
    id_insegnante_corso = InsegnanteCorso.objects.filter(insegnante_id=id).values_list('id', flat=True)
    corsi_ins = Corso.objects.filter(id__in=id_corsi_insegnante)
    lezioni = Lezione.objects.filter(insegnantecorso_id__in=id_insegnante_corso)

    return render(request, 'lezioni/gestione_lezioni.html', {'lezioni': lezioni, 'corsi_ins': corsi_ins})


@insegnante_only
@login_required
def save_lezione(request, form, template_name):
    data = dict()
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            data['form_is_valid'] = True
            id_insegnante_corso = InsegnanteCorso.objects.filter(insegnante_id=request.user.id).values_list('id',
                                                                                                            flat=True)
            lezioni = Lezione.objects.filter(insegnantecorso_id__in=id_insegnante_corso)
            data['html_lezioni_list'] = render_to_string('lezioni/lista_lezioni.html', {'lezioni': lezioni})
        else:
            data['form_is_valid'] = False

    context = {'form': form}
    data['html_form'] = render_to_string(template_name, context, request=request)
    return JsonResponse(data)


@insegnante_only
@login_required
def crea_lezione(request):
    if request.method == 'POST':
        form = LezioneForm(request.POST, user=request.user.id)
    else:
        form = LezioneForm(user=request.user.id)
    return save_lezione(request, form, 'lezioni/crea_lezione.html')


@insegnante_only
@login_required
def update_lezione(request, pk):
    lezione = get_object_or_404(Lezione, pk=pk)
    if request.method == 'POST':
        form = LezioneForm(request.POST, instance=lezione, user=request.user.id)
    else:
        form = LezioneForm(instance=lezione, user=request.user.id)
    return save_lezione(request, form, 'lezioni/update_lezione.html')


@insegnante_only
@login_required
def delete_lezione(request, pk):
    lezione = get_object_or_404(Lezione, pk=pk)
    data = dict()
    if request.method == 'POST':
        lezione.delete()
        data['form_is_valid'] = True
        id_insegnante_corso = InsegnanteCorso.objects.filter(insegnante_id=request.user.id).values_list('id', flat=True)
        lezioni = Lezione.objects.filter(insegnantecorso_id__in=id_insegnante_corso)
        data['html_lezioni_list'] = render_to_string('lezioni/lista_lezioni.html', {'lezioni': lezioni})
    else:
        context = {'lezione': lezione}
        data['html_form'] = render_to_string('lezioni/delete_lezione.html', context, request=request)

    return JsonResponse(data)


@login_required
def prenotazioni(request, id):
    lezioni = Prenotazione.objects.filter(user_id=id)
    return render(request, 'lezioni/prenotazioni.html', {'lezioni': lezioni})


class Prenota(LoginRequiredMixin, TemplateView):
    def get(self, request):
        user_id = request.GET.get('user', None)
        lez_id = request.GET.get('lezione', None)
        user = GymUser.objects.get(id=user_id)
        lezione = Lezione.objects.get(id=lez_id)
        prenotazione = Prenotazione(user=user, lezione=lezione)
        prenotazione.save()
        data = {
            'added': True
        }
        return JsonResponse(data)


class DeletePrenotazione(LoginRequiredMixin, DeleteView):
    def get(self, request):
        id_prenot = request.GET.get('id', None)
        Prenotazione.objects.get(id=id_prenot).delete()
        data = {
            'deleted': True
        }
        return JsonResponse(data)

EnerGym_folder/lezioni/templates/lezioni/crea_lezione.html
<form method="post" action="{% url 'lezioni:crea_lezione' %}" class="crea-lezione-form">
    {% csrf_token %}
    <div class="modal-header">
        <h6 class="modal-title">Crea lezione</h6>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <div class="modal-body">
        {% include 'lezioni/lezione_form.html' %}
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Chiudi</button>
        <button type="submit" class="btn btn-primary">Aggiungi</button>
    </div>
</form>

EnerGym_folder/lezioni/templates/lezioni/delete_lezione.html
<form method="post" action="{% url 'lezioni:delete_lezione' lezione.id %}" class="delete-lezione-form">
    {% csrf_token %}
    <div class="modal-header">
        <h6 class="modal-title">Vuoi eliminare la lezione?</h6>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <div class="modal-body">
        <p class="lead">Sei sicuro di voler eliminare la lezione in programma? <strong>{{ lezione.insegnantecorso.corso.nome }}</strong> del giorno <strong>{{ lezione.data }}</strong></p>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Chiudi</button>
        <button type="submit" class="btn btn-danger">Rimuovi</button>
    </div>
</form>

EnerGym_folder/lezioni/templates/lezioni/gestione_lezioni.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Lezioni{% endblock %}

{% block style %}
    <style>
        body {
            background-image: url('{% static 'img/img3.jpg' %}');
            -webkit-background-size: cover;
            -moz-background-size: cover;
            -o-background-size: cover;
            background-size: cover;
        }

        #bodytable{
            background-color: rgba(255,255,255, 0.8);
        }
    </style>
{% endblock %}

{% block body %}
    <div class="main">
        <h1 align="center" style="padding-bottom: 20px">Le mie lezioni</h1>
        <div class="row">
            <div class="col-md-12">
                <div>
                    <div class="container-fluid">
                        <div  class="col-sm-2" style="float: left">
                            <button style="margin-bottom: 10px" type="button" class="btn btn-primary crea-lezione my_btn" data-url="{% url 'lezioni:crea_lezione' %}">
                                Aggiungi lezione
                            </button>
                            <p><b>I tuoi corsi:</b></p>
                            <ul>
                                {% for corso in corsi_ins %}
                                    <li><p>{{ corso.nome }}</p></li>
                                {% endfor %}
                            </ul>
                        </div>
                        <div class="col-sm-10" style="float: left">
                            <table class="table table-striped" id="table-lezioni" style="width:100%">
                                <thead>
                                <tr>
                                    <th class="text-center">Corso</th>
                                    <th class="text-center">Descrizione</th>
                                    <th class="text-center">Posti Disponibili</th>
                                    <th class="text-center">Quando?</th>
                                    <th class="text-center"> Modifica/Elimina</th>
                                </tr>
                                </thead>
                                <tbody id="bodytable">
                                {% include 'lezioni/lista_lezioni.html' %}
                                </tbody>
                            </table>
                            <div class="modal fade" id="modal-lezione">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block script %}
    <script>

        $(function () {

            var loadForm = function () {
                var btn = $(this);
                $.ajax({
                    url: btn.attr("data-url"),
                    type: 'get',
                    dataType: 'json',
                    beforeSend: function () {
                        $("#modal-lezione .modal-content").html("");
                        $("#modal-lezione").modal("show");
                    },
                    success: function (data) {
                        $("#modal-lezione .modal-content").html(data.html_form);
                    }
                });
            };

            var saveForm = function () {
                var form = $(this);
                $.ajax({
                    url: form.attr("action"),
                    data: form.serialize(),
                    type: form.attr("method"),
                    dataType: 'json',
                    success: function (data) {
                        if (data.form_is_valid) {
                            $("#table-lezioni tbody").html(data.html_lezioni_list);
                            $("#modal-lezione").modal("hide");
                        }
                        else {
                            $("#modal-lezione .modal-content").html(data.html_form);
                        }
                    }
                });
                return false;
            };


            // Crea lezione
            $(".crea-lezione").click(loadForm);
            $("#modal-lezione").on("submit", ".crea-lezione-form", saveForm);

            // Update lezione
            $("#table-lezioni").on("click", ".update-lezione", loadForm);
            $("#modal-lezione").on("submit", ".update-lezione-form", saveForm);

            //Delete lezione
            $("#table-lezioni").on("click", ".delete-lezione", loadForm);
            $("#modal-lezione").on("submit", ".delete-lezione-form", saveForm);

        });

    </script>

{% endblock %}

EnerGym_folder/lezioni/templates/lezioni/lezione_form.html
{% load widget_tweaks %}

{% for field in form %}
  <div class="form-group{% if field.errors %} has-error{% endif %}">
    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
    {% render_field field class="form-control" %}
    {% for error in field.errors %}
      <p class="help-block">{{ error }}</p>
    {% endfor %}
  </div>
{% endfor %}

EnerGym_folder/lezioni/templates/lezioni/lezioni.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Lezioni{% endblock %}

{% block style %}
    <style>
        body {
            background-image: url('{% static 'img/img10.jpg' %}');
            -webkit-background-size: cover;
            -moz-background-size: cover;
            -o-background-size: cover;
            background-size: cover;
        }

        #bodytable{
            background-color: rgba(255, 255, 255, 0.8);
        }

    </style>
{% endblock %}

{% block body %}
    <div class="main">
        <h1 align="center" style="padding-bottom: 10px">Lezioni in programma</h1>
        <span class="col-sm-3">
            <form class="form-inline" method="GET" action="">
                <input class="form-control" type="text" name="q" id="myInput" value="{{ request.GET.q }}" aria-label="Search" placeholder="Cerca lezioni..."/>
                <input class="btn btn-success" type="submit" value="Cerca"/>
            </form>
        </span>
        <table class="table table-striped" id="table-data" style="width:100%">
            <thead>
            <tr>
                <th class="text-center">Corso</th>
                <th class="text-center">Istruttore</th>
                <th class="text-center">Descrizione</th>
                <th class="text-center">Posti Disponibili</th>
                <th class="text-center">Quando?</th>
                <th class="text-center"></th>
            </tr>
            </thead>
            <tbody id="bodytable">
            {% for lezione in lezioni %}
                <tr>
                    <td class="text-center"><a href="{% url "gestione_palestra:corso_info" lezione.insegnantecorso.corso.pk %}" target="_blank">{{ lezione.insegnantecorso.corso.nome }}</a></td>
                    <td class="text-center"><a href="{% url "gestione_palestra:insegnante_info" lezione.insegnantecorso.insegnante.pk %}" target="_blank">{{ lezione.insegnantecorso.insegnante.last_name }}</a></td>
                    <td class="text-center">{{ lezione.descrizione }}</td>
                    <td class="text-center">{{ lezione.return_posti_rimasti }}/{{ lezione.posti_disponibili_tot }}</td>
                    <td class="text-center">{{ lezione.data }}</td>

                    {% if lezione.non_disponibile %}
                        <td class="text-center">
                            <a style="color:white" type="button" class="btn btn-warning">Non disponibile</a>
                        </td>
                    {% else %}
                        {% if lezione in lezioni_prenotate%}
                            <td class="text-center">
                                <a style="color:white" type="button" class="btn btn-success">Iscritto</a>
                            </td>
                        {% elif lezione.posti_finiti %}
                            <td class="text-center">
                                <a style="color:white" type="button" class="btn btn-danger">Posti esauriti</a>
                            </td>
                        {% else %}
                            <td class="text-center">
                                <a type="button" class="btn btn-secondary my_btn" style="color: white" onclick="AddPrenot({{user.id }},{{ lezione.id }})">Iscriviti</a>
                            </td>
                        {% endif %}
                    {% endif %}
                </tr>
            {% empty %}
                <tr>
                    <td colspan="5" class="text-center bg-warning">Nessuna lezione in programma</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <script>
        function AddPrenot(user,lezione) {
            var action = confirm("Vuoi iscriverti alla lezione?");
            if (action != false) {
                $.ajax({
                    url: '{% url "lezioni:prenota" %}',
                    data: {
                        'user': user,
                        'lezione':lezione
                    },
                    dataType: 'json',
                    success: function (data) {
                        if(data.added){
                            $("#table-data").load(window.location + " #table-data");
                        }
                    }
                });
            }
        }
    </script>

{% endblock %}

{% block script %}
{% endblock %}

EnerGym_folder/lezioni/templates/lezioni/lista_lezioni.html
{% for lezione in lezioni %}
    <tr>
        <td class="text-center">{{ lezione.insegnantecorso.corso.nome }}</td>
        <td class="text-center">{{ lezione.descrizione }}</td>
        <td class="text-center">{{ lezione.return_posti_rimasti }}/{{ lezione.posti_disponibili_tot }}</td>
        <td class="text-center">{{ lezione.data }}</td>
        <td class="text-center">
            <button type="button" class="btn btn-primary update-lezione" data-url="{% url 'lezioni:update_lezione' lezione.pk %}">
                Modifica
            </button>
            <button type="button" class="btn btn-danger delete-lezione" data-url="{% url 'lezioni:delete_lezione' lezione.pk %}">
                Rimuovi
            </button>
        </td>
    </tr>
{% empty %}
    <tr>
        <td colspan="5" class="text-center bg-warning">Nessuna lezione in programma</td>
    </tr>
{% endfor %}

EnerGym_folder/lezioni/templates/lezioni/prenotazioni.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Lezioni{% endblock %}

{% block style %}
    <style>
        body {
            background-image: url('{% static 'img/img4.jpg' %}');
            -webkit-background-size: cover;
            -moz-background-size: cover;
            -o-background-size: cover;
            background-size: cover;
        }

    </style>
{% endblock %}

{% block body %}
    <div class="main">
        <h1 align="center" style="padding-bottom: 20px">Lezioni prenotate</h1>
        <table class="table table-striped" style="background-color: rgba(255,255,255, 0.8);" id="table-data" style="width:100%">
            <thead>
            <tr>
                <th class="text-center">Corso</th>
                <th class="text-center">Istruttore</th>
                <th class="text-center">Descrizione</th>
                <th class="text-center">Quando?</th>
                <th class="text-center"></th>
            </tr>
            </thead>
            <tbody id="bodytable">
            {% for prenotazione in lezioni %}

                <tr id="{{ prenotazione.id }}">
                    <td class="text-center"><a href="{% url "gestione_palestra:corso_info" prenotazione.lezione.insegnantecorso.corso.pk %}" target="_blank">{{  prenotazione.lezione.insegnantecorso.corso.nome }}</a></td>
                    <td class="text-center"><a href="{% url "gestione_palestra:insegnante_info" prenotazione.lezione.insegnantecorso.insegnante.pk %}" target="_blank">{{ prenotazione.lezione.insegnantecorso.insegnante.last_name }}</a></td>
                    <td class="text-center">{{  prenotazione.lezione.descrizione }}</td>
                    <td class="text-center">{{  prenotazione.lezione.data }}</td>
                    {% if prenotazione.lezione.non_disponibile %}
                        <td class="text-center">
                            <a type="button" class="btn btn-success" style="color:white">Trascorsa</a>
                        </td>
                    {% else %}
                        <td class="text-center">
                            <a type="button" class="btn btn-danger my_btn" style="color:white" onclick="deletePrenot({{ prenotazione.id }})">Non posso partecipare</a>
                        </td>
                    {% endif %}

                </tr>
            {% empty %}
                <tr>
                    <td colspan="5" class="text-center bg-warning">Nessuna lezione prenotata</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <script>
        function deletePrenot(id) {
            var action = confirm("Cancellare l'iscrizione?");
            if (action != false) {
                $.ajax({
                    url: '{% url "lezioni:delete_prenotazione" %}',
                    data: {
                        'id': id,
                    },
                    dataType: 'json',
                    success: function (data) {
                        if (data.deleted) {
                            $("#table-data #text-" + id).remove();
                        }
                        $("#table-data").load(window.location + " #table-data");
                    }
                });
            }
        }
    </script>
{% endblock %}

{% block script %}
{% endblock %}

EnerGym_folder/lezioni/templates/lezioni/update_lezione.html
<form method="post" action="{% url 'lezioni:update_lezione' form.instance.pk  %}" class="update-lezione-form">
    {% csrf_token %}
    <div class="modal-header">
        <h6 class="modal-title">Aggiorna lezione</h6>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <div class="modal-body">
        {% include 'lezioni/lezione_form.html' %}
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Chiudi</button>
        <button type="submit" class="btn btn-primary">Aggiorna</button>
    </div>
</form>